### ISSUE TITLE
【報告】Taggedテーブルにレコードが1000件を超えるとタグフィルターでエラーになる。

### ISSUE THREAD

**Issue by I-chi-jo-ji** [ambiesoft/SceneExplorer#6]
件名通り、Taggedテーブルにレコードを1000件を超えて登録すると、タグでフィルターした際にエラーになります。
![tag](https://user-images.githubusercontent.com/64514437/80561783-8e58eb00-8a20-11ea-9ef3-9276cc1297cd.jpg)

**Comment by ambiesoft** [comment]
こんにちは
報告ありがとうございます。
多くのデータでのテストをしてませんでした。
確認して直したいです

**Comment by I-chi-jo-ji** [comment]
ご返信ありがとうございました。
修正いただけると、ひたすらタグ打ちしていた作業も報われます。

また何かあれば報告させていただきます。
引き続きよろしくお願いいたします。

**Comment by ambiesoft** [comment]
v1.21.15にて対応

**Comment by I-chi-jo-ji** [comment]
エラーが出なくなっていること確認致しました。
早々のご対応、ありがとうございました。
